apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: nextjs
          image: nextjsappacr.azurecr.io/nextjsapp:sandbox
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: nextjs-config
            - secretRef:
                name: nextjs-secret
